### ISSUE TITLE
The figures are not updated any longer

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#119]
Hi, 

See https://yangcatalog.org/private/figures/IETFYANGPageCompilation.png

And I wonder if this one is updated correctly?
https://yangcatalog.org/private/figures/IETFCiscoAuthorsYANGPageCompilation.png

Regards, B.

**Comment by miroslavKovacPantheon** [comment]
Hello,


This has been fixed.


Thank you

________________________________
Od: bclaise <notifications@github.com>
Odoslané: pondelok, 11. mája 2020 9:43:41
Komu: YangCatalog/backend
Kópia: Subscribed
Predmet: [YangCatalog/backend] The figures are not updated any longer (#119)


Hi,

See https://yangcatalog.org/private/figures/IETFYANGPageCompilation.png

And I wonder if this one is updated correctly?
https://yangcatalog.org/private/figures/IETFCiscoAuthorsYANGPageCompilation.png

Regards, B.

**Comment by bclaise** [comment]
Thanks. Can you explain the bump at https://yangcatalog.org/private/figures/IETFYANGOutOfRFC.png

**Comment by miroslavKovacPantheon** [comment]
hi,


not sure what bump do you see, maybe it is in cache of your browser? try to reload with ctrl + shift + r .... I don t have any bump there or maybe I am not sure of which you are talking about.. Attaching my printscreen.


Thank you

Miroslav Kovac

________________________________
Od: bclaise <notifications@github.com>
Odoslané: pondelok, 11. mája 2020 17:44:47
Komu: YangCatalog/backend
Kópia: Miroslav Kováč; Comment
Predmet: Re: [YangCatalog/backend] The figures are not updated any longer (#119)


Thanks. Can you explain the bump at https://yangcatalog.org/private/figures/IETFYANGOutOfRFC.png

**Comment by bclaise** [comment]
I meant that the last horizontal line of graph shows something like 115 YANG models, then 116, then 115 again.

**Comment by miroslavKovacPantheon** [comment]
Hi,


It took me a while to figure this out but it s because of the xym app. This application was updated recently and is much more strict about some rules how the code begins and end should look ant it is causing it to drop after we upgraded.. on yang2.amls.com it s even more strict and it drops little more.


Not sure if this is good or we should be able to find this modules anyway. I may create some less strict rule for rfc documents.


this is how the code begins should look like


   <CODE BEGINS> file "ietf-netconf-nmda@2019-01-07.yang"

   module ietf-netconf-nmda {


this is the one module bump that is currently missing (RFC5717)


    <CODE BEGINS>

    module ietf-netconf-partial-lock {


and this is the example of the one missing from dockerized verision (RFC6470)


<CODE BEGINS> file="ietf-netconf-notifications@2011-12-09.yang"

 module ietf-netconf-notifications {


the equals sign is not recognized from the regexp


regards

Miroslav Kovac

________________________________
Od: bclaise <notifications@github.com>
Odoslané: utorok, 12. mája 2020 9:53:21
Komu: YangCatalog/backend
Kópia: Miroslav Kováč; Comment
Predmet: Re: [YangCatalog/backend] The figures are not updated any longer (#119)


I meant that the last horizontal line of graph shows something like 115 YANG models, then 116, then 115 again.

**Comment by miroslavKovacPantheon** [comment]
hi,


Adding Einar since he is mergins xym.


Hi Einar if you follow the conversation you ll find out that some of the rfc documents are made the way that xym can not extract the yang file at the moment. Please if you don t agree with the following please let me know.


I did a little research and according to https://tools.ietf.org/html/rfc6087#section-3.1


and then keywords that say

1<https://tools.ietf.org/html/rfc2119#section-1>. MUST
 This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an absolute requirement of the specification.

3<https://tools.ietf.org/html/rfc2119#section-3>. SHOULD
 This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course

I am going to update the code that these will be valid as well. The

file "name@revision.yang"

is under shoud. only code begins and code ends tags are under must and therefore required to be in there.


I will create a PR and let you know Einar.


Regrads,

Miroslav Kovac

________________________________
Od: Miroslav Kováč
Odoslané: utorok, 12. mája 2020 11:11:07
Komu: YangCatalog/backend; YangCatalog/backend
Kópia: Comment
Predmet: Re: [YangCatalog/backend] The figures are not updated any longer (#119)


Hi,


It took me a while to figure this out but it s because of the xym app. This application was updated recently and is much more strict about some rules how the code begins and end should look ant it is causing it to drop after we upgraded.. on yang2.amls.com it s even more strict and it drops little more.


Not sure if this is good or we should be able to find this modules anyway. I may create some less strict rule for rfc documents.


this is how the code begins should look like


   <CODE BEGINS> file "ietf-netconf-nmda@2019-01-07.yang"

   module ietf-netconf-nmda {


this is the one module bump that is currently missing (RFC5717)


    <CODE BEGINS>

    module ietf-netconf-partial-lock {


and this is the example of the one missing from dockerized verision (RFC6470)


<CODE BEGINS> file="ietf-netconf-notifications@2011-12-09.yang"

 module ietf-netconf-notifications {


the equals sign is not recognized from the regexp


regards

Miroslav Kovac

________________________________
Od: bclaise <notifications@github.com>
Odoslané: utorok, 12. mája 2020 9:53:21
Komu: YangCatalog/backend
Kópia: Miroslav Kováč; Comment
Predmet: Re: [YangCatalog/backend] The figures are not updated any longer (#119)


I meant that the last horizontal line of graph shows something like 115 YANG models, then 116, then 115 again.

**Comment by miroslavKovacPantheon** [comment]
This issue has been fixed and solved
