### ISSUE TITLE
fix repoutil tests

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#189]
some tests are not working since authorization is failing. we need to change the repo owner anyway.

**Comment by SlavomirMazurPantheon** [comment]
After [doc repository was removed](https://github.com/YangCatalog/deployment/issues/98) some other tests failed too.
This was caused by pulling non-existing doc repository, because we use this repo: https://github.com/Sergej-Testerko/deployment which is not up-to-date.
However, we do not have access to this repository anymore, so we should replace this by [yang-catalog](https://github.com/yang-catalog?tab=repositories) repo.
