### ISSUE TITLE
RFC document as not flagge as RFCs

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#49]
Hi, 

https://www.yangcatalog.org/yang-search/module_details.php?module=ietf-i2rs-rib@2018-04-23.yang
It points to the:
document-name : | draft-ietf-i2rs-rib-data-model-15.txt
reference : | http://datatracker.ietf.org/doc/draft-ietf-i2rs-rib-data-model

The RFCs should be point to RFC information
document-name : | RFC8431
reference : | https://datatracker.ietf.org/doc/rfc8431/

Also why is the compilation-status : | unknown ?
For all RFCs, we want to fill in this info:
module-classification : | unknown

**Comment by miroslavKovacPantheon** [comment]
Hi


This module is still draft as far as I can tell and expired even. 2018-09-13 should be RFC.. nevertheless some metadata about this module are wrong.. like document-name should point to draft-ietf-i2rs-rib-data-model-14.txt not 15 which is RFC.. also the reference should point to older version. These metadata are taken out of json files that are produced from your script that is now updated and that are now in yc.o I see one problem now and that is  reference will always point to the latest because at the time that script is parsing it, it will create url to the latest which is http://datatracker.ietf.org/doc/draft-ietf-i2rs-rib-data-model which now is equal to http://datatracker.ietf.org/doc/draft-ietf-i2rs-rib-data-model/15 but before it was http://datatracker.ietf.org/doc/draft-ietf-i2rs-rib-data-model/14..


This modules was also populated in old.yangcatalog.org and grabed from there and moved to new. that s why we have compilation-status : | unknown... about module-classification. there is no script that can resolve this. This is populate as something else then uknown only if it is populated using api and module-classification is set by the user.


We can discuss this deeper on todays call..


Regards

Miroslav Kovac

________________________________
Od: bclaise <notifications@github.com>
Odoslané: streda, 19. decembra 2018 14:39:34
Komu: YangCatalog/backend
Kópia: Subscribed
Predmet: [YangCatalog/backend] RFC document as not flagge as RFCs (#49)


Hi,

https://www.yangcatalog.org/yang-search/module_details.php?module=ietf-i2rs-rib@2018-04-23.yang
It points to the:
document-name : | draft-ietf-i2rs-rib-data-model-15.txt
reference : | http://datatracker.ietf.org/doc/draft-ietf-i2rs-rib-data-model

The RFCs should be point to RFC information
document-name : | RFC8431
reference : | https://datatracker.ietf.org/doc/rfc8431/

Also why is the compilation-status : | unknown ?
For all RFCs, we want to fill in this info:
module-classification : | unknown

**Comment by miroslavKovacPantheon** [comment]
This was populated correctly closing the issue for draft pointing at: [draft](https://www.yangcatalog.org/yang-search/module_details.php?module=ietf-i2rs-rib@2018-04-23), for rfc pointing at [RFC](https://www.yangcatalog.org/yang-search/module_details.php?module=ietf-i2rs-rib@2018-09-13)
