### ISSUE TITLE
Check old ietf drafts from yangModels repo and remove them 

### ISSUE THREAD

**Issue by miroslavKovacPantheon** [YangCatalog/backend#55]
Remove old draft ietf modules from yangModels repository if they are not needed any more.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

after communicating with Einar, I created a PR in which I removed the experimental/ietf/SYSLOG-MODEL directory - https://github.com/YangModels/yang/pull/1116
This folder contained IETF drafts that had already expired, but are maintained by the IETF.
Since the latest version of the draft model is in https://github.com/YangModels/yang/tree/master/standard/ietf/DRAFT we won’t lose anything and mentioned directory can be safely removed.

Regards,
Slavomir Mazur
