### ISSUE TITLE
ValueError in create_vendors_data_dict() method

### ISSUE THREAD

**Issue by SlavomirMazurPantheon** [YangCatalog/backend#572]
Following Exception can be found in `redisModulesConnection.log` file:
```
Traceback (most recent call last):
  File "/backend/redisConnections/redisConnection.py", line 240, in create_vendors_data_dict
    vendor_name, platform_name, software_version_name, software_flavor_name = key.replace('#', ' ').split('/')
ValueError: too many values to unpack (expected 4)
```
Check whether this part of functionality works correctly and what causes this error/exception,

**Comment by richardzilincikPantheon** [comment]
The error is caused by cisco's [`RSP2/RSP3`](https://github.com/YangModels/yang/blob/af90c053a1ca9b01a3f229e313e4af7e5b849c87/vendor/cisco/xe/1693/platform-metadata.json#L146) platform. We need to change the separator used is redis vendor keys to make it possible to have slashes present in platform names.
