### ISSUE TITLE
Need for a monitoring system

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/backend#79]
We need a monitoring system to proactively understand when something goes wrong with the YANGcatalog:
- a process being down
- an API not responding
- "YANG Catalog is under maintenance or restart"
- etc.

A msg to the YANG catalog admin webex teams, or email, or whatever, seems appropriate.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

since YANG Catalog runs in AWS, we use several features that AWS offers.
Route 53
    - This sends requests to selected endpoints, which checks whether the services are running properly
    - If a problem occurs, a notification is sent to the email
Cloudwatch
    - We monitor and analyze utilization of server (CPU, RAM) and identify when there is an increase machine resources
We implemented dashboard to the ADMIN UI, which is also sending requests to the key service like - ES, Redis, ConfD, yangvalidator API, NGINX ...
Results of cronjob runs are also displayed on this dashboard + we are notified if some cronjob fails.

I think we can close this issue for now.
In case you have an idea how to improve or adjust existing monitoring methods, please create a new Github issue with a description.

Regards,
Slavomir Mazur
